travis:
  secure:
    BINSTAR_TOKEN: WuqbauLYwmjGvgM+/62+JxkN/0rvraJYoL/wg5suIiq/X69HzLqMW1kD4UuUmhgNV3F9dFFCOgmh/C9lflZSAa4m2BcPXd3VLtIa+27SjiknZWEeCHucJrllDAbYgAm3yzQE0SSYsLPFH5paVQnJDKQ7pZR86HenDRBO/Xzf7GurOzNAPxfFQ1PB/JylCrWwfYrT/ybZv2Pk/ScRCtfjpVVzORPmD192VDfnrJjHB+atdFz/i1O2tl9gK8wevOVJoobFUWvryG2FXfg4IXaHwf9XbpUJDZBcvaXvoG63i0JDRS+N95nzj2d0XROJ9hOXcXki9sVCU6L9k8YWx1pXv0A57xr7NeHrsETbEULIafUTuMu+EsOIt1ROEtvebCTB0r1bj7prdFVIsOtgLANMFPeRWgVICEhRaOiaNVslORtdCBv9Gu6JhSNi2sEBVbClnYsDdMOZNds7JqWZE4+3eooY2ayZS2SdUl7mBJ1EQTIYzhsBXIoYQ9iAEvVoRVvfUa8TrXS2VK9MPcqmhJ/kMMxnCnn2kfoEsofBgDJNkvmrd1PXfWpBEC0I3Y9lkA8rMp2K+v68gaCxFyCtAf0CDDosCPB/ENx2+gqSvthMWG6oabFQbBwbVbPyTErpjUPaORQwxIs06PuuGbqjaXt3PEuQrSU6Y/XrXFzZgUH1XJM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
